export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCEEDED = "FETCH_USER_SUCCEEDED";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_UPDATED_USER_REQUEST = "FETCH_UPDATED_USER_REQUEST";
export const FETCH_UPDATED_USER_SUCCEEDED = "FETCH_UPDATED_USER_SUCCEEDED";
export const FETCH_UPDATED_USER_FAILURE = "FETCH_UPDATED_USER_FAILURE";

export const FETCH_CHAT_REQUEST = 'FETCH_CHAT_REQUEST';
export const FETCH_CHAT_SUCCEEDED = 'FETCH_CHAT_SUCCEEDED';
export const FETCH_CHAT_FAILURE = 'FETCH_CHAT_FAILURE';

export const REMOVE_CHAT = 'REMOVE_CHAT';

export const SET_ACTIVE_USERS = 'SET_ACTIVE_USERS';
